<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
    <RootNamespace>EBAssistant.Adapter</RootNamespace>
    <AssemblyName>EBAssistant.Adapter2024</AssemblyName>
    <PlatformTarget>x86</PlatformTarget>
    <DefineConstants>TRACE;EB31</DefineConstants>
    <NoWarn>0649</NoWarn>
    <OutputPath>..\..\bin\Debug\net10.0-windows\Adapters\2024\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Accessibility" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Xml" />
    <Reference Include="UIAutomationClient" />
    <Reference Include="UIAutomationTypes" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\AdapterProgram.cs"><Link>AdapterProgram.cs</Link></Compile>
  </ItemGroup>
  <ItemGroup>
    <COMReference Include="Aucotec">
      <WrapperTool>tlbimp</WrapperTool><VersionMinor>0</VersionMinor><VersionMajor>31</VersionMajor>
      <Guid>{101D8CF0-E1D8-11D2-B72E-00805F52B443}</Guid><Lcid>0</Lcid><Isolated>false</Isolated><EmbedInteropTypes>false</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
